
// Objective-C API for talking to the following Go packages
//
//	github.com/mekhriddin/V2RaySabLab/XrayKit
//
// File is generated by gomobile bind. Do not edit.
#ifndef __XrayKit_FRAMEWORK_H__
#define __XrayKit_FRAMEWORK_H__

#include "Xraykit.objc.h"
#include "Universe.objc.h"

#endif
