// Objective-C API for talking to github.com/mekhriddin/V2RaySabLab/XrayKit Go package.
//   gobind -lang=objc github.com/mekhriddin/V2RaySabLab/XrayKit
//
// File is generated by gobind. Do not edit.

#ifndef __Xraykit_H__
#define __Xraykit_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Start parses configJSON (Xray "config v5" JSON shape) and starts the core.
Returns nil on success, an error otherwise. Idempotent guard: returns
an error if the core is already running — caller should Stop first.
 */
FOUNDATION_EXPORT BOOL XraykitStart(NSData* _Nullable configJSON, NSError* _Nullable* _Nullable error);

/**
 * Stop tears down the running core. Safe to call when not running.
 */
FOUNDATION_EXPORT BOOL XraykitStop(NSError* _Nullable* _Nullable error);

/**
 * Version returns the embedded Xray-core version string.
 */
FOUNDATION_EXPORT NSString* _Nonnull XraykitVersion(void);

#endif
